[env:bootloader]
platform = ststm32
board = nucleo_f407zg
framework = stm32cube

build_flags =
    -DSTM32F407xE
    -DHAL_UART_MODULE_ENABLED
    -DHAL_FLASH_MODULE_ENABLED
    -DHAL_GPIO_MODULE_ENABLED
    -DHAL_RCC_MODULE_ENABLED

lib_deps =
    stm32cube

upload_protocol = stlink
debug_tool = stlink
